CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory_Finance" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Finance" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260104164857_InitialFinance') THEN
    CREATE TABLE "Transactions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TxnDate" timestamp with time zone NOT NULL,
        "DescriptionRaw" text NOT NULL,
        "DescriptionClean" text,
        "Amount" numeric(18,2) NOT NULL,
        "AccountFrom" text,
        "AccountTo" text,
        "Category" text,
        "Source" text NOT NULL,
        "SourceRef" text,
        "Mapped" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260104164857_InitialFinance') THEN
    INSERT INTO "__EFMigrationsHistory_Finance" ("MigrationId", "ProductVersion")
    VALUES ('20260104164857_InitialFinance', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260110102751_AddUniqueSourceRefIndex') THEN
    CREATE UNIQUE INDEX "IX_Transactions_Source_SourceRef" ON "Transactions" ("Source", "SourceRef") WHERE "Source" = 'pdf' AND "SourceRef" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260110102751_AddUniqueSourceRefIndex') THEN
    INSERT INTO "__EFMigrationsHistory_Finance" ("MigrationId", "ProductVersion")
    VALUES ('20260110102751_AddUniqueSourceRefIndex', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    ALTER TABLE "Transactions" ADD COLUMN IF NOT EXISTS "ClosingBalance" numeric NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    ALTER TABLE "Transactions" ADD COLUMN IF NOT EXISTS "Skipped" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    CREATE TABLE "CostBasisOverrides" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Isin" character varying(12) NOT NULL,
        "InstrumentName" text,
        "InvestedAmount" numeric(18,6) NOT NULL,
        "Reason" text,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CostBasisOverrides" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    CREATE TABLE "HoldingsSnapshots" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StatementDate" timestamp with time zone NOT NULL,
        "InvestorName" text,
        "SourceFileName" text NOT NULL,
        "StoredFileName" text,
        "FileHash" character varying(64) NOT NULL,
        "UploadedAt" timestamp with time zone NOT NULL,
        "ReportedInvested" numeric(18,6),
        "ReportedMarketValue" numeric(18,6),
        "ReportedTotalReturn" numeric(18,6),
        "ReportedReturnPct" numeric(9,4),
        "TotalInvested" numeric(18,6) NOT NULL,
        "TotalMarketValue" numeric(18,6) NOT NULL,
        "TotalReturn" numeric(18,6) NOT NULL,
        "ReturnPct" numeric(9,4) NOT NULL,
        "ParseWarnings" text,
        CONSTRAINT "PK_HoldingsSnapshots" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    CREATE TABLE "Holdings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SnapshotId" integer NOT NULL,
        "AssetClass" integer NOT NULL,
        "RowOrder" integer NOT NULL,
        "Name" text NOT NULL,
        "Isin" character varying(12),
        "Account" text,
        "Category" text,
        "Units" numeric(18,6),
        "UnitPrice" numeric(18,6),
        "InvestedReported" numeric(18,6) NOT NULL,
        "Invested" numeric(18,6) NOT NULL,
        "MarketValue" numeric(18,6) NOT NULL,
        "TotalReturnReported" numeric(18,6) NOT NULL,
        "TotalReturn" numeric(18,6) NOT NULL,
        "Xirr" numeric(9,4),
        "PortfolioWeightReported" numeric(9,4),
        "IsAggregate" boolean NOT NULL,
        "ExcludedFromTotals" boolean NOT NULL,
        "GroupKey" text NOT NULL,
        "CostBasisAdjusted" boolean NOT NULL,
        "AdjustmentNote" text,
        CONSTRAINT "PK_Holdings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Holdings_HoldingsSnapshots_SnapshotId" FOREIGN KEY ("SnapshotId") REFERENCES "HoldingsSnapshots" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    INSERT INTO "CostBasisOverrides" ("Id", "CreatedAt", "InstrumentName", "InvestedAmount", "IsActive", "Isin", "Reason", "UpdatedAt")
    VALUES (1, TIMESTAMPTZ '2026-07-26T00:00:00Z', 'Tata Capital Ltd.', 14996.0, TRUE, 'INE976I01016', 'IPO allotment; Value Research reports no cost basis for this holding.', TIMESTAMPTZ '2026-07-26T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    CREATE UNIQUE INDEX "IX_CostBasisOverrides_Isin" ON "CostBasisOverrides" ("Isin");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    CREATE INDEX "IX_Holdings_Isin" ON "Holdings" ("Isin");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    CREATE INDEX "IX_Holdings_SnapshotId" ON "Holdings" ("SnapshotId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    CREATE UNIQUE INDEX "IX_HoldingsSnapshots_FileHash" ON "HoldingsSnapshots" ("FileHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    CREATE UNIQUE INDEX "IX_HoldingsSnapshots_StatementDate" ON "HoldingsSnapshots" ("StatementDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    PERFORM setval(
        pg_get_serial_sequence('"CostBasisOverrides"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "CostBasisOverrides") + 1,
            nextval(pg_get_serial_sequence('"CostBasisOverrides"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory_Finance" WHERE "MigrationId" = '20260726073800_AddHoldingsSnapshots') THEN
    INSERT INTO "__EFMigrationsHistory_Finance" ("MigrationId", "ProductVersion")
    VALUES ('20260726073800_AddHoldingsSnapshots', '8.0.0');
    END IF;
END $EF$;
COMMIT;

