// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Data;

#nullable disable

namespace api.Migrations.FinanceDb
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260809100541_AddTransactionHistory")]
    partial class AddTransactionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.Models.CostBasisOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstrumentName")
                        .HasColumnType("text");

                    b.Property<decimal>("InvestedAmount")
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Isin")
                        .IsUnique();

                    b.ToTable("CostBasisOverrides", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstrumentName = "Tata Capital Ltd.",
                            InvestedAmount = 14996m,
                            IsActive = true,
                            Isin = "INE976I01016",
                            Reason = "IPO allotment; Value Research reports no cost basis for this holding.",
                            UpdatedAt = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("api.Models.Holding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<string>("AdjustmentNote")
                        .HasColumnType("text");

                    b.Property<int>("AssetClass")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<bool>("CostBasisAdjusted")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExcludedFromTotals")
                        .HasColumnType("boolean");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Invested")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("InvestedReported")
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("IsAggregate")
                        .HasColumnType("boolean");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PortfolioWeightReported")
                        .HasColumnType("numeric(9,4)");

                    b.Property<int>("RowOrder")
                        .HasColumnType("integer");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalReturn")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("TotalReturnReported")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Units")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Xirr")
                        .HasColumnType("numeric(9,4)");

                    b.HasKey("Id");

                    b.HasIndex("Isin");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Holdings", (string)null);
                });

            modelBuilder.Entity("api.Models.HoldingsSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InvestorName")
                        .HasColumnType("text");

                    b.Property<string>("ParseWarnings")
                        .HasColumnType("text");

                    b.Property<decimal?>("ReportedInvested")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("ReportedMarketValue")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("ReportedReturnPct")
                        .HasColumnType("numeric(9,4)");

                    b.Property<decimal?>("ReportedTotalReturn")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("ReturnPct")
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StatementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoredFileName")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalInvested")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("TotalMarketValue")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("TotalReturn")
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.HasIndex("StatementDate")
                        .IsUnique();

                    b.ToTable("HoldingsSnapshots", (string)null);
                });

            modelBuilder.Entity("api.Models.InvestmentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .HasColumnType("text");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("AssetClass")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BalanceAmount")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("BalanceQuantity")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Brokerage")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImportId")
                        .HasColumnType("integer");

                    b.Property<string>("InstrumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Isin")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MarketValue")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("RowOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TxnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.HasIndex("Isin");

                    b.HasIndex("ImportId", "TxnDate");

                    b.ToTable("InvestmentTransactions", (string)null);
                });

            modelBuilder.Entity("api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountFrom")
                        .HasColumnType("text");

                    b.Property<string>("AccountTo")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<decimal?>("ClosingBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionClean")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Mapped")
                        .HasColumnType("boolean");

                    b.Property<bool>("Skipped")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRef")
                        .HasColumnType("text");

                    b.Property<DateTime>("TxnDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Source", "SourceRef")
                        .IsUnique()
                        .HasFilter("\"Source\" = 'pdf' AND \"SourceRef\" IS NOT NULL");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("api.Models.TransactionHistoryImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("FirstTxnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvestorName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastTxnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParseWarnings")
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .HasColumnType("text");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StatementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StoredFileName")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalDividends")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("TotalInvested")
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.HasIndex("StatementDate")
                        .IsUnique();

                    b.ToTable("TransactionHistoryImports", (string)null);
                });

            modelBuilder.Entity("api.Models.Holding", b =>
                {
                    b.HasOne("api.Models.HoldingsSnapshot", "Snapshot")
                        .WithMany("Holdings")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("api.Models.InvestmentTransaction", b =>
                {
                    b.HasOne("api.Models.TransactionHistoryImport", "Import")
                        .WithMany("Transactions")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Import");
                });

            modelBuilder.Entity("api.Models.HoldingsSnapshot", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("api.Models.TransactionHistoryImport", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
